### ISSUE TITLE
大佬我想问一问关于udp获取到数据的解析

### ISSUE THREAD

**Issue by v200123** [ningjx/F1-2020-Telemetering-Tools#1]
我在使用udp获取到二进制数组后，将其直接转换为字符串，但是显示出来的却是乱码，请问这个是需要什么特殊处理么，我用的是Java来显示

**Comment by ningjx** [comment]
数据包里存储的不是字符串，你需要根据官方文档给出的数据类型及其长度，还有每个字段的长度，按文档给出的字段顺序依次取值。
例如：文档给出“Each packet has the following header”每个UDP数据包都会给出一个报文头（用来标识游戏版本、数据包信息类型等等），并给出了Header里每个字段的大小，如下
![image](https://user-images.githubusercontent.com/38414820/183299326-7f86173e-d5ab-4c7f-999a-36e14ced4bf8.png)
所以对于收到的字节流，我们只需要按照图示顺序，按指定长度将字节取出转换即可。即：字节流的0,1两个字节，应该转换为 字段“m_packetFormat”的值，2位置的字节，转换为m_gameMajorVersion的值，以此类推。
通常来讲，程序一般都会使用设计好的协议来传输数据，而不是直接使用字符串，这样的好处很多，就不展开了

**Comment by v200123** [comment]
感谢大佬解惑，主要之前一直处理的是json格式，遇到这个就不知道咋处理了
